# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Kodeo' do

pod 'Alamofire'
pod 'EZSwiftExtensions'
pod 'PullToBounce'
pod 'DGElasticPullToRefresh'
pod 'MGSwipeTableCell'
pod 'EZLoadingActivity'
pod 'DZNEmptyDataSet'

end

target 'KodeoTests' do

end

target 'KodeoUITests' do

end

